default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: connect-genkihirano_production
  username: root
  password: <%= ENV['DATABASE_PRO_PASSWORD'] %>
