default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000
  host: db

development:
  <<: *default
  database: connect_development

test:
  <<: *default
  database: connect_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: connect_genkihirano_production
  username: postgres
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:hostname] %>