default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: connect-genkihirano_development

test:
  <<: *default
  database: connect-genkihirano_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: connect-genkihirano_production
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
